spring:
  application:
    name: admin-service
  config:
    import: optional:configserver:http://localhost:8888

feign:
  httpclient:
    enabled: true
  client:
    config:
      user-service:        # ← @FeignClient(name="user-service")
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: basic

