spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    bootstrap:
      enabled: false

server:
  compression:
    enabled: false

