# 실행하려는 서비스(컨테이너)들을 정의
services:
  # 1. Config Server
  config-server:
    build: ./config/config-server  # ⭐️ 경로 수정
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - msa-network

  # 2. Discovery Service (Eureka)
  discovery-service:
    build: ./services/discovery-service # ⭐️ 경로 수정
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - msa-network
    depends_on:
      - config-server
    environment:
      - SPRING_CONFIG_URI=http://config-server:8888

  # 3. Gateway Service
  gateway-service:
    build: ./services/gateway-service # ⭐️ 경로 수정
    container_name: gateway-service
    ports:
      - "8000:8000"
    networks:
      - msa-network
    depends_on:
      - discovery-service
    environment:
      - SPRING_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  # 4. User Service
  user-service:
    build: ./services/user-service # ⭐️ 경로 수정
    container_name: user-service
    networks:
      - msa-network
    depends_on:
      - discovery-service
    environment:
      - SPRING_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  # 5. News Service
  news-service:
    build: ./services/news-service # ⭐️ 경로 수정
    container_name: news-service
    networks:
      - msa-network
    depends_on:
      - discovery-service
    environment:
      - SPRING_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

#  # 6. Flask API (최종 수정)
  flaskapi:
    build: ./services/flaskapi
    #    ports: ["5000:5000"]                # ← 임시 외부 노출
    networks: [msa-network]
    environment:
      - TZ=Asia/Seoul
        - EUREKA_ENABLED=false
        - DATABASE_URL=sqlite:////app/instance/app.db
        - CORS_ALLOWED_ORIGINS=http://localhost:300
    volumes:
      - ./services/flaskapi/instance:/app/instance
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 2s
      retries: 12
    restart: unless-stopped

# 서비스들이 사용할 공용 네트워크 정의
networks:
  msa-network:
    driver: bridge