server:
  port: 8086

spring:
  application:
    name: tooltip-service

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    bootstrap:
      enabled: false
# 곧 삭제
# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  # 여기까지
  cache:
    type: redis
    redis:
      time-to-live: 24h
      cache-null-values: false

  data:
    redis:
      host: localhost
      port: 6379
