# 1. 서버 포트 설정
server:
  port: 8082

# 2. Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

# 3. Actuator 엔드포인트 노출 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# 4. 로깅 레벨 설정
logging:
  level:
    com.newnormallist.newsservice: DEBUG
    org.springframework.security: WARN

# (추가) 요약 기능 추가 설정
summarizer:
  base-url: http://flaskapi:5000   # 도커 브리지 네트워크 서비스명