# 1. 서버 포트 설정
server:
  port: 8081
  forward-headers-strategy: framework

# 2. Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

# 3. Actuator 엔드포인트 노출 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# 4. 로깅 레벨 설정
logging:
  level:
    com.newnormallist.userservice: DEBUG
    org.springframework.security: TRACE
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE


# 5. swagger 설정
springdoc:
  forward-headers-enabled: true # 게이트웨이에서 전달된 헤더를 사용
  # 이 서비스의 API 문서(JSON 파일)를 어떤 경로에 만들지 결정
  api-docs:
    path: /user-api-docs
  # 2. 이 서비스 단독으로 Swagger UI 페이지를 보고 싶을 때 사용할 경로 (개발/테스트용)
  swagger-ui:
    path: /user-swagger-ui.html
  # 3. 게이트웨이에서 이 서비스를 식별할 그룹 정보 설정
  group-configs:
    - group: user-service
      paths-to-match:
        - /api/users/**
        - /api/auth/** # auth API도 문서에 포함

app:
  gateway-url: http://localhost:8000 # 게이트웨이 URL (개발/테스트용)

# 6. oauth 설정
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:8000/api/auth/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            # 카카오 서버의 엔드포인트 주소들
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
oauth2:
  redirect:
    frontend-callback-url: http://localhost:3000/oauth/callback # 프론트엔드 리다이렉트 URL (개발/테스트용)