spring:
  datasource:
    url: jdbc:mysql://mysql.macacolabs.site:3322/newsdb
    username: nnl
    password: nnl1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: newnewscorps@gmail.com
    password: stvvkgemhrmgttlb

jwt:
  secret: 9WbhujDz1MK5t55au7k7B8AOY512A8hvDoSs4DWD+Gg=