spring:
  application:
    name: news-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    bootstrap:
      enabled: false
server:
  port: 8082

logging:
  level:
    com.newnormallist.newsservice: DEBUG
    org.springframework.web: DEBUG