server:
  port: 8083
  servlet:
    context-path: /news-service

spring:
  application:
    name: news-service
  profiles:
    active: dev

  # Spring Cloud Config 비활성화 (개발 환경용)
  cloud:
    config:
      enabled: false

  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:mysql://mysql.macacolabs.site:3322/newsdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:nnl}
    password: ${DB_PASSWORD:nnl1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 시작 시 스키마를 업데이트합니다.
    show-sql: true # 실행되는 SQL 쿼리를 로그로 보여줍니다.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true # SQL 쿼리를 보기 좋게 정렬합니다.
        use_sql_comments: true # SQL 쿼리에 주석을 추가합니다.

# Eureka 클라이언트 설정 (활성화)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true  # Eureka 클라이언트 활성화
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Spring Boot Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 로깅 레벨 설정
logging:
  level:
    com.newnormallist.newsservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
