server:
  port: 8082

spring:
  application:
    name: news-service
  config:
    import: optional:configserver:http://localhost:8888
  elasticsearch:
    uris: http://localhost:9200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

crawler:
  schedule:
    cron: "0 0 */2 * * *" # 2???? ??
  sources:
    - name: "????"
      url: "https://www.yna.co.kr"
      selector: ".headline-list li"
    - name: "????"
      url: "https://www.chosun.com"
      selector: ".story-card"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.newsservice.news: DEBUG