# IDE에서 직접 실행할 때만 적용될 설정
spring:
  config:
    # Config Server의 주소를 로컬 IP로 변경
    import: configserver:http://192.168.0.38:8888

eureka:
  client:
    service-url:
      # Eureka Server의 주소를 로컬 IP로 변경
      defaultZone: http://192.168.0.38:8761/eureka/

# 로컬 개발 환경용 설정 오버라이드
services:
  dedup:
    # 로컬에서 실행 중인 Python 서비스
    url: http://192.168.0.38:8084
