spring:
  application:
    name: crawler-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 크롤러 스케줄링 설정 (개발 중에는 비활성화)
crawler:
  scheduling:
    enabled: false # 정식 스케줄 비활성화 (수동 실행만)
    test-enabled: false # 테스트 스케줄 비활성화

# 파일서버 설정
fileserver:
  base-path: http://dev.macacolabs.site:8008/1

# Python 중복제거 서비스 설정
services:
  dedup:
    url: http://localhost:8084
    timeout: 300 # 5분 타임아웃
    fileserver-path: http://dev.macacolabs.site:8008/1 # Python 서비스도 같은 경로 사용
