# 로컬 MySQL 연결(예시 값은 실제에 맞게 변경)
spring:
  datasource:
    url: jdbc:mysql://mysql.macacolabs.site:3322/newsdb
    username: nnl            # ← 로컬/개인용 계정
    password: nnl1234

# JWT/토큰(있는 프로젝트만)
security:
  jwt:
    secret: 9WbhujDz1MK5t55au7k7B8AOY512A8hvDoSs4DWD+Gg=       # ← 로컬 테스트용 시크릿

## 외부 API 키(있는 프로젝트만)
#external:
#  openai:
#    api-key: ""                  # 예시
#flask:
#  api-key: ""                    # 예시
