server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthenticationFilter
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/api/news/**
        - id: newsletter-service
          uri: lb://newsletter-service
          predicates:
            - Path=/api/newsletter/**
          filters:
            - name: AuthenticationFilter
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - name: AuthenticationFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: your-jwt-secret-key
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
