server:
  port: 8082

spring:
  application:
    name: news-service
  datasource:
    url: jdbc:mysql://localhost:3306/news_db?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  elasticsearch:
    uris: http://localhost:9200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

crawler:
  schedule:
    cron: "0 0 */2 * * *" # 2시간마다 실행
  sources:
    - name: "연합뉴스"
      url: "https://www.yna.co.kr"
      selector: ".headline-list li"
    - name: "조선일보"
      url: "https://www.chosun.com"
      selector: ".story-card"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.newsservice.news: DEBUG
