spring:
  application:
    name: news-service
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: newnewscorps@gmail.com
    password: stvvkgemhrmgttlb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true