version: '3.8'

services:
  dedup-service:
    build: .
    container_name: dedup-service
    ports:
      - '8084:8084'
    environment:
      # 환경 변수 설정
      - ENVIRONMENT=docker

      - EUREKA_SERVER=http://eureka:8761/eureka
      - DEBUG=false
      - LOG_LEVEL=INFO

    networks:
      - msa-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8084/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  msa-network:
    external: true
    # 기존 MSA 네트워크 사용
