# IDE에서 직접 실행할 때만 적용될 설정
spring:
  config:
    # Config Server의 주소를 localhost로 변경
    #    import: configserver:http://192.168.0.38:8888
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      # Eureka Server의 주소를 localhost로 변경
      #      defaultZone: http://192.168.0.38:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

services:
  news-service:
    url: http://localhost:8082